- name: This playbook is to test the installation and starting the nginx
  hosts: localhost
  become: true 
  tasks:
  - name: This task is to install the nginx
    ansible.builtin.yum:
      ame: nginx
      state: latest
  - name: This task is to start the nginx service
    ansible.builtin.service:
      name: nginx
      state: started