- name: This palybook is to test the variables
  hosts: app
  become: true 
  vars:
    name: padmasrikanth
    age: 34
    profession: enginner
  tasks:
  - name: This playbook is to test the variables
    ansible.builtin.debug:
      msg: My name is padma srikanth kakarla

  - name: This playbook is to test the variables
    ansible.builtin.debug:
      msg: My name is {{name}}, and my age is {{age}} and my profession is {{profession}}
  