- name: This playbook is to call the variables from the inventory level
  hosts: db 
  become: true
  tasks:
  - name: This task is to display varibales from inventory
    ansible.builtin.debug:
      msg: My db user name is {{db_username}} and my db password is {{db_pass}}